### ISSUE TITLE
Add json tags for explicit serilization

### ISSUE THREAD

**Issue by deef0000dragon1** [gempir/go-twitch-irc#112] opened 2019-12-16 17:32 UTC
I am isolating the section of my program that accepts twitch IRC in a separate micro-service from the section that actually does stuff, with a redis pub/sub in-between. The ask is for JSON tags to be added so that the message structs can be easily serialized and de-serialized with explicit tags.

I would be willing to write the PR if this is acceptable.

**Comment by gempir** [comment] 2019-12-16 17:40
I wouldn't decline such a PR, but usally it's best pratice to abstract away that part of the application to not create a tight coupling to go-twitch-irc.

**Comment by deef0000dragon1** [comment] 2019-12-19 22:16
Mostly? I am an idiot and forgot that they will serialize by default. Mind, that doesn't mean that I don't plan on making the PR anyway. I have used this project too much to not TRY to help in some manner.

**Comment by gempir** [comment] 2019-12-20 19:55
I'll close this, since there seems to be no issue present.

**Closed by gempir** 2019-12-20 19:55 UTC

**Comment by techygrrrl** [comment] 2023-05-28 04:14
Hi @gempir, are you open to re-opening this issue (as a feature request, not a bug since there is no bug) and accepting a contribution to add JSON struct tags for serializing the fields?

The fields automatically translate using PascalCase but I was wondering if you'd be open to a contribution that added JSON struct tags for snake_case capitalization. 

For example, your existing pong struct:

```go
// PongMessage describes an IRC PONG message
type PongMessage struct {
	Raw     string
	Type    MessageType
	RawType string

	Message string
}
```

Would be changed to this:

```go
// PongMessage describes an IRC PONG message
type PongMessage struct {
	Raw     string      `json:"raw"`
	Type    MessageType `json:"type"`
	RawType string      `json:"raw_type"`
	
	Message string      `json:"message"`
}
```

This would result in the existing JSON, which is serialized using PascalCase:

```json
{
  "Raw": ":tmi.twitch.tv PONG tmi.twitch.tv :go-twitch-irc",
  "Type": 12,
  "RawType": "PONG",
  "Message": "go-twitch-irc"
}
```

To be turned into this format that uses snake case instead:

```json
{
  "raw": ":tmi.twitch.tv PONG tmi.twitch.tv :go-twitch-irc",
  "type": 12,
  "raw_type": "PONG",
  "message": "go-twitch-irc"
}
```

I would change all message types to all message listeners, e.g. `client.OnXMessage(message)` where `X` is the struct that will be transformed:

https://github.com/gempir/go-twitch-irc/blob/e01cb7b7c21f28057a0eddc14416887acd0cc7a3/client.go#L382-L399

It's quite a bit of manual work that I'm happy to do since I want conventional casing for my JSON, but I just wanted to check that you're open to the contribution before I make this change.

This would cause a breaking change to any users of your library that rely on the default marshalling of your structs. Since you don't explicitly support JSON serialization, maybe that's ok, but something to consider.

In [this message](https://github.com/gempir/go-twitch-irc/issues/112#issuecomment-566165191) you mentioned:

> I wouldn't decline such a PR, but usally it's best pratice to abstract away that part of the application to not create a tight coupling to go-twitch-irc.

I'm also open to an alternate suggestion to get the desired casing, but I wanted to avoid manually mapping the fields myself into new structs to avoid the potential for human error where I may forget to map a field. 

Let me know your thoughts and if you're open to snake case JSON tags. Thanks!

**Comment by gempir** [comment] 2023-05-28 06:30
No sorry, I'm against it. 

I don't see why you can't work with the current PascalCase. 

If another project prefers kebab case then they had a problem as well. Either Map the data or keep using the PascalCase

**Comment by techygrrrl** [comment] 2023-05-28 09:31
Thanks for the consideration.

> No sorry, I'm against it.

That's fair. I guess a lot can change in a few years—[in a post above](https://github.com/gempir/go-twitch-irc/issues/112#issuecomment-566165191) you mentioned you weren't opposed to such a contribution, why the change of heart?

<img width="930" alt="image" src="https://github.com/gempir/go-twitch-irc/assets/88961088/7d3aead2-3ce0-4cf6-9560-fe76a85b1eb8">

> I don't see why you can't work with the current PascalCase.
> If another project prefers kebab case then they had a problem as well. 

This is also a fair argument, but most projects use a more conventional style for JSON, and that convention tends to be snake case. I cannot remember the last API I used that used PascalCase. Here's a few popular developer API's I can think of, all using snake case: 

- **the [Twitch API](https://dev.twitch.tv/docs/api/reference/#get-channel-followers)** – probably the most relevant in this case—arguably the library should be consistent with the Twitch API
- [Paypal](https://developer.paypal.com/api/rest/requests/)
- [Stripe](https://stripe.com/docs/api/disputes/object)
- [Spotify](https://developer.spotify.com/documentation/web-api/reference/get-track)

The gempir/go-twitch-irc library is not the only library in my project, but its JSON sticks out like a sore thumb due to its unconventional formatting. 

That said, this issue is not unsurmountable, but it would be ideal if the most popular Go library for working with Twitch IRC would be consistent with Twitch's API standards and use snake case JSON.

**Comment by gempir** [comment] 2023-05-28 09:42
It's fair to say PascalCase is a bit more unusual, bit in the end it's very much personal preference. Personally If I had the choice I would use camelCase. 

But in the spirit of not breaking API, I don't see the point of changing this. Yes it's not really an "api" and it was more implicit. 
But I'm sure a lot of people still marshalled the data to json somewhere. 

If you so heavily want to use snake case, like I said write your own structs and map them. This should always be done in a good application. 

I'm not just saying it to avoid your request. I do this myself in my applications. Example: https://github.com/gempir/justlog/blob/main/api/server.go#L90
